version: '3.3'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
  redis:
    image: redis
    command: redis-server --requiredpass redis --appendonly yes
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data/redis

volumes:
  mongodbdata:
  rabbitmqdata:
  redisdata:
